# Generated by Django 3.2.18 on 2023-04-20 11:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('level', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000)])),
                ('score', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
            ],
        ),
    ]
